"""empty message

Revision ID: 4ef90d1e7b8b
Revises: 64b873c0f0af
Create Date: 2022-03-31 10:40:09.003443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ef90d1e7b8b'
down_revision = '64b873c0f0af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tag', sa.Column('title', sa.String(length=100), nullable=True))
    op.drop_column('tag', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tag', sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('tag', 'title')
    # ### end Alembic commands ###
