"""empty message

Revision ID: 81969adbc007
Revises: 4ef90d1e7b8b
Create Date: 2022-03-31 11:16:15.564979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81969adbc007'
down_revision = '4ef90d1e7b8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_tags',
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post_tags')
    # ### end Alembic commands ###
